### ISSUE TITLE
Unexpected message issued by crictl when tagging and then removing an image

### ISSUE THREAD

**Issue by wlei27** [kubernetes-sigs/cri-tools#1276]
#### What happened:
Have an image in my local repository
```
~$ sudo crictl images
IMAGE                         TAG                 IMAGE ID            SIZE
docker.io/library/alpine      latest              7e01a0d0a1dcd       7.63MB
```
Tag this image, specifying a version v1.0
```
~$ sudo podman tag alpine docker.io/library/alpine:v1.0
```
Display the local images from crictl and see both the original and tagged images
```
~$ sudo crictl images
IMAGE                         TAG                 IMAGE ID            SIZE
docker.io/library/alpine      latest              7e01a0d0a1dcd       7.63MB
docker.io/library/alpine      v1.0                7e01a0d0a1dcd       7.63MB
```
Delete the original image from my local respository, and crictl issues a message that it is removing both images
```
~$ sudo crictl rmi alpine
Deleted: docker.io/library/alpine:latest
Deleted: docker.io/library/alpine:v1.0
```
A subsequent display shows the tagged image was not removed, as expected.
```
lei:~$ sudo crictl images
IMAGE                         TAG                 IMAGE ID            SIZE
docker.io/library/alpine      v1.0                7e01a0d0a1dcd       7.63MB
```
#### What you expected to happen:
Only issue the message about removed/untagged image
#### How to reproduce it (as minimally and precisely as possible):
See the first paragraph.
#### Environment:

- Container runtime or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
~$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
lei:~$ 

```
- Kernel (e.g. `uname -a`):
```
~$ uname -a
Linux li-d148f310-ab49-11e1-8d16-26d9f4d03e00.ibm.com 6.2.9-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:32:58 UTC 2023 x86_64 GNU/Linux
lei:~$ 
```
- Others:

**Comment by haircommander** [comment]
I think this is more of a cri-o bug (assuming you're using cri-o as the CRI impl). Does it happen when you don't do the podman tag between?

**Comment by wlei27** [comment]
If I don't do the podman tag,  the same image `alpine` (7e01a0d0a1dcd) only has 1 tag (i.e. latest).  When doing `crictl rmi alpine`, the image will be `deleted`.  

If the same image (i.e. `alpine` or `7e01a0d0a1dcd`) has 2 and more tag (i.e. latest and v1.0 in my test), it only be untagged when doing `crictl rmi `.  That is : the image will not be deleted until it only has 1 tag.

This is the cri-o behavior.  And it's same for Podman and Docker.
```
~$ sudo podman images
REPOSITORY                   TAG         IMAGE ID      CREATED       SIZE
docker.io/library/alpine     v1.0        7e01a0d0a1dc  2 months ago  7.63 MB
docker.io/library/alpine     latest      7e01a0d0a1dc  2 months ago  7.63 MB
~$ sudo podman rmi alpine
Untagged: docker.io/library/alpine:latest
~$ 
~$ sudo podman images
REPOSITORY                   TAG         IMAGE ID      CREATED       SIZE
docker.io/library/alpine     v1.0        7e01a0d0a1dc  2 months ago  7.63 MB
~$ 
~$ sudo podman rmi alpine:v1.0
Untagged: docker.io/library/alpine:v1.0
Deleted: 7e01a0d0a1dcd9e539f8e9bbd80106d59efbdf97293b3d38f5d7a34501526cdb
~$ 
```

```
~$ sudo docker images
REPOSITORY   TAG       IMAGE ID       CREATED       SIZE
alpine       latest    8ca4688f4f35   11 days ago   7.34MB
alpine       v1.0      8ca4688f4f35   11 days ago   7.34MB
~$ sudo docker rmi alpine
Untagged: alpine:latest
~$ sudo docker images
REPOSITORY   TAG       IMAGE ID       CREATED       SIZE
alpine       v1.0      8ca4688f4f35   11 days ago   7.34MB
~$ sudo docker rmi alpine:v1.0
Untagged: alpine:v1.0
Untagged: alpine@sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978
Deleted: sha256:8ca4688f4f356596b5ae539337c9941abc78eda10021d35cbc52659c74d9b443
Deleted: sha256:cc2447e1835a40530975ab80bb1f872fbab0f2a0faecf2ab16fbbb89b3589438
~$ sudo docker images
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
~$ 
```

**Comment by haircommander** [comment]
digging into it a bit, this seems like expected behavior: https://github.com/cri-o/cri-o/blob/main/internal/storage/image.go#L702

basically, even though one image is being "removed" cri-o is not keeping track whether there are other containers using a different image name with the same ID. Instead, it just untags for that image, and assumes the kubelet will request it remove the other image name when that's appropriate

cc @mtrmac

**Comment by mtrmac** [comment]
Good timing, see https://github.com/cri-o/cri-o/pull/7375/commits/2fd4073c44b48ee24e4606f5fcb16ef8db81f07a  in https://github.com/cri-o/cri-o/pull/7375 .

- AFAICT the output of `crictl` is entirely a bug in `crictl`: https://github.com/kubernetes-sigs/cri-tools/blob/f8733ddf69f86dae2d40e9f690785ef4bdb4440e/cmd/crictl/image.go#L453-L455 doesn’t know what was deleted, and even if it were correct about the _intended semantics_ of the `RemoveImage` operation, that implementation is incorrect because the set of tags could have changed between `crictl`’s calls of `ImageStatus` and `RemoveImage`. This just doesn’t work. If `crictl` wants to correctly list tag changes, I suppose it needs to call `ImageStatus` before and after (but that would still not allow differentiating between changes done by this `RemoveImage` and changes done by some other CRI client). Probably best for `crictl delete` to just say nothing. (Or, alternatively, extend the CRI to return the information about what the server actually did.)
- Unless I have missed something, Kubelet only ever calls `RemoveImage` with a full image ID (as part of the “remove unused images” control loop), so handling of names is … basically irrelevant. 
- OTOH https://github.com/cri-o/cri-o/pull/7375/commits/572339120d9b4a6c2822828a2e86afffd2acebd2#diff-73f26dcabd7e433970fc0612ff0068d2d8f7cd61dda790bcd603195197aaad97R709 — it might be better for Kubelet to only request removal of tags (only tags that Kubelet created, even? but that’s not well-defined), and then we would need an atomic c/storage “untag or delete” operation. IMHO this is all mostly theoretical — the principle of the thing is that K8s “owns” the node and any concurrent image/tag updates are an exception that needs to bend to the K8s needs, not the other way around. But I don’t feel strongly about that.

**Comment by Bharadwajshivam28** [comment]
If anyone not working then I can take a look into it
