### ISSUE TITLE
provide a brew package

### ISSUE THREAD

**Issue by bcollard** [kubernetes-sigs/cri-tools#587]
Hello,

Now that Docker Desktop proposes a nice experience for running a local Kubernetes cluster, it would be great to take advantage of crictl on Mac.
I saw this issue #573 for Darwin support, so I guess it's a prerequisite.
Could you help with producing a brew recipe please?

**Comment by saschagrunert** [comment]
Hey @bcollard, thank you for the request. I'm not familiar with brew but I would expect that we have to put the recipe into their repositories, right? We're planning to publish the debs/rpms directly via the Kubernetes release engineering (see https://github.com/kubernetes/release/issues/739). Do you think we can point the brew formula (or its contents) to the same resources?

**Comment by johscheuer** [comment]
There are two possible ways:
- do the same like [isitoctl](https://github.com/Homebrew/homebrew-core/blob/master/Formula/istioctl.rb) and [kubectl](https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubernetes-cli.rb) which means compile `crictl` with go.
- Download the precompiled binaries and install these

I would assume that the both examples both are manually/community managed (which doesn't mean a bot should/cloud open a PR).

**Comment by 111andre111** [comment]
I have a question: Can we get some drive into this topic?

**Comment by badouralix** [comment]
Hi everyone, just wanted to mention that https://github.com/Homebrew/homebrew-core/blob/25ee35c01fcd68e1cb0b382ca8919918bde3793e/Formula/cri-tools.rb was recently released

Use this command to install both `crictl` and `critest`

```bash
brew update && brew install cri-tools
```

Currently it follows the pattern of https://github.com/Homebrew/homebrew-core/blob/25ee35c01fcd68e1cb0b382ca8919918bde3793e/Formula/kubernetes-cli.rb and compiles the cri tools from scratch ( only once to build the bottle, and people actually download the bottle instead of recompiling the cri tools themselves )

Happy to work with the release engineering team to migrate to precompiled binaries if it provides some value
