### ISSUE TITLE
crictl info get wrong container runtime cgroupdrives when use containerd. 

### ISSUE THREAD

**Issue by oldthreefeng** [kubernetes-sigs/cri-tools#728]
#### What happened:

config crictl.yaml 
```
$ crictl --version
crictl version 1.16.1
$ crictl  version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.3.9
RuntimeApiVersion:  v1alpha2

$ cat  /etc/crictl.yaml
runtime-endpoint: unix:///run/containerd/containerd.sock
```

config contianerd for systemd cgroupdriver
```
$  containerd config  default  > /etc/containerd/config.toml

# add systemd cgroupdriver to  /etc/containerd/config.toml

  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true

$ systemctl restart containerd
```
Use crictl to get cri informations.  it returns false. 

```
$ crictl info |grep system
    "systemdCgroup": false,
```

#### What you expected to happen:
like this: 
```
$ crictl info |grep system
    "systemdCgroup": true,
```

#### Environment:
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
$ uname -a
Linux louis-master 5.8.0-44-generic #50-Ubuntu SMP Tue Feb 9 06:29:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ containerd --version
containerd github.com/containerd/containerd v1.3.9 ea765aba0d05254012b0b9e595e995c09186427f
```

**Comment by saschagrunert** [comment]
@mikebrow PTAL

**Comment by mikebrow** [comment]
Apologies. The output of the runc options is crippled because of the failure of toml to dump the contents of toml.Primative https://github.com/containerd/containerd/blob/master/pkg/cri/config/config.go#L52

The field you grep'd is deprecated: 
https://github.com/containerd/containerd/blob/master/pkg/cri/config/config_unix.go#L61
https://github.com/containerd/containerd/blob/master/pkg/cri/config/config.go#L214-L217

as you can see ^ the field you are seeing in your grep is set by systemd_cgroup at the higher level.

This is the commit that removed that field from the docs: https://github.com/containerd/cri/commit/b74653b8213f362a26e00335bed6cf27452c7757#diff-77b3519370ff48f6caf7c316f0ece966f2f0871c40e9381d451d2c5b1c76b40f

The runc option you set should be working, albeit we are not outputting runc options in the info.

**Comment by adisky** [comment]
We can close this issue It has been fixed in  https://github.com/containerd/containerd/pull/5300
/close
