### ISSUE TITLE
Add support for k8s 1.23 Pod Sandbox and New Stats

### ISSUE THREAD

**Issue by bobbypage** [kubernetes-sigs/cri-tools#841]
#### What would you like to be added:

K8s 1.23 added new CRI RPCs for pod sandbox and more detailed container stats. See kubernetes/enhancements#2371 for the k8s upstream issue.

kubernetes/kubernetes#102789 added the CRI fields namely PodSandboxStats, ListPodSandboxStats and some new fields for CPU and memory container stats.

`crictl` should be able to display the new Pod Sandbox Stats as well as the new cpu and memory container stats. 

xref: 
https://github.com/containerd/containerd/issues/6112 / https://github.com/containerd/containerd/pull/6113
kubernetes/kubernetes#102789

/cc @haircommander @qiutongs @mikebrow

**Comment by saschagrunert** [comment]
Sounds great, are you happy to work on this @bobbypage?

**Comment by saschagrunert** [comment]
Did a test with https://github.com/kubernetes-sigs/security-profiles-operator/pull/796 and it does not work, because:

- we usually fallback to the in-memory btf (which is now available within that patch) if no vmlinux is exposed. The vmlinux file is available on the azure node.
- forcing it to use the in-memory btf fails with the same error

That's odd, I'm not sure if the kernel configuration of the azure nodes are correct to support our BPF application.

**Comment by saschagrunert** [comment]
@bobbypage do you still consider working on this one?
